# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 0.1.5

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: client/docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
   - requirements: client/docs/requirements.txt
