[package]
name = "tinychain"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.12"
bytes = "0.5"
ed25519-dalek = "1.0.0-pre.3"
futures = "0.3"
futures-util = "0.3"
hyper = "0.13"
rand = "0.7"
regex = "1.3"
semver = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8"
structopt = "0.3"
tokio = { version = "0.2", features = ["fs", "macros"] }
url = "2.1"
