[package]
name = "tinychain"
version = "0.4.1"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "A next-gen database + application server"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["distributed", "transactional", "host", "platform", "runtime"]
categories = ["concurrency", "database-implementations", "data-structures", "hardware-support", "web-programming"]

[lib]
name = "tinychain"
path = "src/lib.rs"

[[bin]]
name = "tinychain"
path = "src/main.rs"

[features]
tensor = ["afarray", "tc-tensor"]

[dependencies]
afarray = { version = "~0.7.2", optional = true }
async-trait = "0.1"
bytes = "1.0"
destream = "0.5"
destream_json = { version = "~0.8.3", features = ["tokio-io"] }
env_logger = "0.9"
freqache = "~0.2.4"
futures = "0.3"
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
log = { version = "0.4", features = ["release_max_level_info"] }
num_cpus = "1.13"
pin-project = "1.0"
rjwt = "0.4"
safecast = "0.1"
serde = { version = "1.0", features = [] }
serde_json = { version = "1.0" }
structopt = "0.3"
tbon = "~0.3.5"
tc-btree = "~0.1.7"
tc-error = "~0.2.5"
tc-table = "~0.1.7"
tc-tensor = { version = "~0.2.0", optional = true }
tc-transact = "~0.8.1"
tc-value = "~0.2.1"
tcgeneric = "~0.2.2"
tokio = { version = "1.11", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "time"] }
tokio-util = { version = "0.6", features = ["io"] }
uplock = "~0.1.2"
uuid = "0.8"
url = { version = "2.2" }
