[package]
name = "tinychain"
version = "0.2.1"
authors = ["haydnv"]
edition = "2018"
description = "A next-gen database + application server"
license = "Apache-2.0"
readme = "../README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["distributed", "transactional", "host", "platform", "runtime"]
categories = ["concurrency", "database-implementations", "data-structures", "web-programming"]

[lib]
name = "tinychain"
path = "src/lib.rs"

[[bin]]
name = "tinychain"
path = "src/main.rs"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
destream = "0.3"
destream_json = { version = "~0.5.4", features = ["tokio-io"] }
env_logger = "0.8"
freqache = "~0.2.2"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
log = { version = "0.4", features = ["release_max_level_warn"] }
rjwt = "0.4"
safecast = "0.1"
serde = { version = "1.0", features = [] }
serde_json = { version = "1.0" }
structopt = "0.3"
tbon = "0.1"
tc-btree = { path = "btree" }
tc-error = "0.2"
tc-table = { path = "table" }
tc-transact = { path = "transact" }
tc-value = { path = "value" }
tcgeneric = { path = "generic" }
tokio = { version = "1.5", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "time"] }
tokio-util = { version = "0.6", features = ["io"] }
uplock = "0.1"
uuid = "0.8"
url = { version = "2.2" }
