[package]
name = "tc-tensor"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's Tensor collection type. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "tensor", "gpu", "ml", "parallel"]
categories = ["concurrency", "data-structures", "hardware-support", "mathematics"]

[dependencies]
afarray = "~0.3.4"
arrayfire = "3.8"
async-trait = "0.1"
destream = "0.4"
futures = "0.3"
itertools  = "0.10"
log = { version = "0.4", features = ["release_max_level_warn"] }
num = "0.4"
number-general = "~0.3.7"
num_cpus = "1.13"
safecast = "0.1"
strided = "~0.2.9"
tc-error = { path = "../error", features = ["tensor"] }
tc-value = { path = "../value" }
tc-transact = { path = "../transact", features = ["tensor"] }
tcgeneric = { path = "../generic" }
