[package]
name = "tc-tensor"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's Tensor collection type. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "tensor", "gpu", "ml", "parallel"]
categories = ["concurrency", "data-structures", "hardware-support", "mathematics"]

[dependencies]
afarray = "~0.3.1"
itertools  = "0.10"
number-general = "~0.3.7"
safecast = "0.1"
tc-error = "0.1"
tc-value = { path = "../value" }
tc-transact = { path = "../transact", features = ["tensor"] }
tcgeneric = "~0.1.6"
