[package]
name = "value"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's representation of a value which can be collated and stored"
license = "Apache-2.0"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain"]
categories = ["data structures"]

[dependencies]
addr = "0.2"
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
collate = "0.1"
destream = "0.3"
generic = { path = "../generic" }
log = { version = "0.4", features = [] }
number-general = "0.3"
error = { path = "../error" }
safecast = "0.1"
serde = { version = "1.0", features = []}
