[package]
name = "tc-value"
version = "0.1.8"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's representation of a value which can be collated and stored. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain"]
categories = ["data-structures"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
collate = "~0.1.9"
destream = "0.3"
futures = "0.3"
log = { version = "0.4", features = [] }
number-general = "~0.3.6"
safecast = "0.1"
serde = { version = "1.0", features = []}
tcgeneric = "~0.1.5"
tc-error = "0.2"
