[package]
name = "tc-btree"
version = "0.1.6"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's BTree collection type. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "key-value", "collection"]
categories = ["database", "database-implementations", "data-structures"]

[dependencies]
async-trait = "0.1"
collate = "~0.1.10"
destream = "0.5"
futures = "0.3"
log = { version = "0.4", features = ["release_max_level_warn"] }
num_cpus = "1.13"
safecast = "0.1"
tc-error = "~0.2.4"
tc-transact = "0.8"
tc-value = "~0.1.12"
tcgeneric = "~0.2.1"
uuid = "0.8"
