[package]
name = "tc-btree"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's BTree collection type. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "key-value", "collection"]
categories = ["database", "database-implementations", "data-structures"]

[dependencies]
async-trait = "0.1"
collate = ">=0.1.3"
destream = "0.3"
futures = "0.3"
log = { version = "0.4", features = ["release_max_level_warn"] }
safecast = "0.1"
tbon = "0.1"
tc-error = "0.1"
tc-transact = { path = "../transact" }
tc-value = { path = "../value" }
tcgeneric = { path = "../generic" }
uuid = "0.8"
