[package]
name = "tc-transact"
version = "0.5.0"
authors = ["haydnv"]
edition = "2018"
description = "A Tinychain transaction. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "transaction", "executor"]
categories = ["concurrency", "data-structures"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
destream = "0.3"
env_logger = "0.8"
futures = "0.3"
log = { version = "0.4", features = [] }
rand = "0.7"
serde = { version = "1.0", features = []}
sha2 = "0.9"
destream_json = { version = "0.5", features = ["tokio-io"] }
tcgeneric = { path = "../generic" }
tc-error = "0.2"
tc-value = { path = "../value" }
tokio = { version = "1.5", features = ["io-util"] }
tokio-util = { version = "0.6", features = ["io"] }
uplock = "0.1"
uuid = { version = "0.8", features = ["v4"] }
