[package]
name = "tc-transact"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "A Tinychain transaction. Unstable."
license = "Apache-2.0"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "transaction", "executor"]
categories = ["concurrency", "data structures"]

[dependencies]
async-trait = "0.1"
bytes = "1.0"
destream = "0.3"
env_logger = "0.8"
futures = "0.3"
log = { version = "0.4", features = [] }
rand = "0.7"
serde = { version = "1.0", features = []}
tcgeneric = "0.1"
tc-error = "0.1"
uplock = "0.1"
uuid = { version = "0.8", features = ["v4"] }
