[package]
name = "tc-table"
version = "0.1.1"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's Table collection type. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "table", "collection"]
categories = ["database", "database-implementations", "data-structures"]

[dependencies]
async-trait = "0.1"
collate = "~0.1.9"
destream = "0.3"
futures = "0.3"
log = { version = "0.4", features = ["release_max_level_warn"] }
safecast = "0.1"
tc-btree = "~0.1.1"
tc-error = "0.2"
tc-transact = "0.4"
tc-value = "~0.1.7"
tcgeneric = "~0.1.4"
