[package]
name = "tcgeneric"
version = "0.2.2"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "Generic data types used internally by Tinychain. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

categories = ["data-structures"]

[dependencies]
async-trait = "0.1"
destream = "0.5"
futures = "0.3"
regex = "1.3"
safecast = "0.1"
serde = { version = "1.0", features = [] }
tc-error = "~0.2.5"
uuid = "0.8"
