[package]
name = "tc-error"
version = "0.2.1"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain's generic error struct"
license = "Apache-2.0"
repository = "http://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "error", "service", "mesh"]
categories = ["data-structures", "rust-patterns"]

[features]
tensor = ["afarray"]

[dependencies]
afarray = { version = "~0.4.1", optional = true }
